### PR TITLE
Added Xtend compiler to the Tycho build

### PR DESCRIPTION
**Pull request by spoenemann**
See eclipse/xtext#1066

### CODE REVIEW

**Comment by spoenemann** [comment]
The build keeps crashing with the following error message. I don't see this problem locally. Does anyone have an idea?

```
[INFO] ------------------------------------------------------------------------
[INFO] Building org.eclipse.xtend.ide.common 2.11.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ org.eclipse.xtend.ide.common ---
[INFO] Deleting /var/jenkins_home/workspace/tend_msp_tychoXtendCompiler-SKZG7BB2ICMH6PD57WCRRSXMD7MQSEOOFUVYZAKONTFVCGZH73UQ/org.eclipse.xtend.ide.common/target
[INFO] Deleting /var/jenkins_home/workspace/tend_msp_tychoXtendCompiler-SKZG7BB2ICMH6PD57WCRRSXMD7MQSEOOFUVYZAKONTFVCGZH73UQ/org.eclipse.xtend.ide.common/xtend-gen (includes = [**/*], excludes = [.gitignore])
[INFO] 
[INFO] --- tycho-packaging-plugin:0.26.0:build-qualifier (default-build-qualifier) @ org.eclipse.xtend.ide.common ---
[INFO] The project's OSGi version is 2.11.0.v20170117-0802
[INFO] 
[INFO] --- tycho-packaging-plugin:0.26.0:validate-id (default-validate-id) @ org.eclipse.xtend.ide.common ---
[INFO] 
[INFO] --- tycho-packaging-plugin:0.26.0:validate-version (default-validate-version) @ org.eclipse.xtend.ide.common ---
[INFO] 
[INFO] --- xtend-maven-plugin:2.11.0-SNAPSHOT:compile (default) @ org.eclipse.xtend.ide.common ---
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007efd7ceab04e, pid=13799, tid=0x00007efd7dc20700
#
# JRE version: OpenJDK Runtime Environment (8.0_111-b14) (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.111-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x9204e]
#
# Core dump written. Default location: /var/jenkins_home/workspace/tend_msp_tychoXtendCompiler-SKZG7BB2ICMH6PD57WCRRSXMD7MQSEOOFUVYZAKONTFVCGZH73UQ/core or core.13799
#
# An error report file with more information is saved as:
# /var/jenkins_home/workspace/tend_msp_tychoXtendCompiler-SKZG7BB2ICMH6PD57WCRRSXMD7MQSEOOFUVYZAKONTFVCGZH73UQ/hs_err_pid13799.log
Segmentation fault (core dumped)
```

http://services.typefox.io/open-source/jenkins/job/xtext-xtend/job/msp_tychoXtendCompiler/

**Comment by cdietrich** [comment]
can you do a dmesg on the machine?

**Comment by cdietrich** [comment]
@spoenemann i get the same error on my workstation

**Comment by spoenemann** [comment]
> i get the same error on my workstation

Do you also use OpenJDK?

**Comment by cdietrich** [comment]
yes

**Comment by cdietrich** [comment]
but sometimes i get a different error like

``` 
[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.11.0-SNAPSHOT:compile (default) on project org.eclipse.xtend.ide.common: Execution default of goal org.eclipse.xtend:xtend-maven-plugin:2.11.0-SNAPSHOT:compile failed: A required class was missing while executing org.eclipse.xtend:xtend-maven-plugin:2.11.0-SNAPSHOT:compile: org/eclipse/xtend/core/jvmmodel/XtendJvmModelInferrer$6
``` 

(in the second run if i dont delete .m2)

**Comment by cdietrich** [comment]
from the stack

```
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x147f47]  __memcpy_ssse3_back+0x237
C  [libzip.so+0x6114]
C  [libzip.so+0x3cfd]  Java_java_util_zip_ZipFile_getEntry+0xfd
J 112  java.util.zip.ZipFile.getEntry(J[BZ)J (0 bytes) @ 0x00007ffabd13634e [0x00007ffabd136280+0xce]
J 333 C2 java.util.jar.JarFile.getEntry(Ljava/lang/String;)Ljava/util/zip/ZipEntry; (22 bytes) @ 0x00007ffabd1e8c0c [0x00007ffabd1e88a0+0x36c]
J 1857 C2 sun.misc.URLClassPath$JarLoader.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; (85 bytes) @ 0x00007ffabd5f4174 [0x00007ffabd5f4000+0x174]
J 722 C2 sun.misc.URLClassPath.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; (83 bytes) @ 0x00007ffabd3099b0 [0x00007ffabd3098c0+0xf0]
J 27178 C1 java.net.URLClassLoader$1.run()Ljava/lang/Class; (63 bytes) @ 0x00007ffac21bf5ec [0x00007ffac21bf3e0+0x20c]
J 23006 C2 java.net.URLClassLoader$1.run()Ljava/lang/Object; (5 bytes) @ 0x00007ffabfc0ae94 [0x00007ffabfc0ae60+0x34]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x640caa]
V  [libjvm.so+0x69065d]  JVM_DoPrivileged+0x55d
J 268  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedExceptionAction;Ljava/security/AccessControlContext;)Ljava/lang/Object; (0 bytes) @ 0x00007ffabd1a2095 [0x00007ffabd1a1fc0+0xd5]
J 12773 C2 org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(Ljava/lang/String;)Ljava/lang/Class; (40 bytes) @ 0x00007ffabf501080 [0x00007ffabf500dc0+0x2c0]
J 12775 C2 org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(Ljava/lang/String;)Ljava/lang/Class; (7 bytes) @ 0x00007ffabf56bd08 [0x00007ffabf565160+0x6ba8]
```

**Comment by cdietrich** [comment]
=> maybe there is a broken zip flowing around

running in the project only i get

```
[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.11.0-SNAPSHOT:compile (default) on project org.eclipse.xtend.ide.common: Execution default of goal org.eclipse.xtend:xtend-maven-plugin:2.11.0-SNAPSHOT:compile failed: Unable to load the mojo 'compile' in the plugin 'org.eclipse.xtend:xtend-maven-plugin:2.11.0-SNAPSHOT'. A required class is missing: org/eclipse/xtext/xbase/annotations/XbaseWithAnnotationsStandaloneSetup
```

**Comment by cdietrich** [comment]
on the second rum again another one

```
org.eclipse.xtend:xtend-maven-plugin:2.11.0-SNAPSHOT:compile (default) on project org.eclipse.xtend.ide.common: Execution default of goal org.eclipse.xtend:xtend-maven-plugin:2.11.0-SNAPSHOT:compile failed: java.lang.NoClassDefFoundError: org/eclipse/xtend/core/xtend/impl/XtendInterfaceImplCustom
```

**Comment by cdietrich** [comment]
hmmmm

the classpath says:

data/xtext-xtend/org.eclipse.xtend.core/target/org.eclipse.xtend.core-2.11.0-SNAPSHOT.jar

=> are we NOT using a bootstrap xtend?!?

**Comment by spoenemann** [comment]
It could be that Maven resolves the xtend-maven-plugin classpath to the local projects instead of the bootstrap jars. If I try to compile with 2.11.0.beta2 I get a lot of errors that are probably fixed in the meantime. I'll try again when 2.11.0.RC1 is available.

**Comment by cdietrich** [comment]
hmmm now it works on my machine :( if i doint call install but package only

**Comment by spoenemann** [comment]
The problem seems to be the circular dependency between the Xtend compiler and the local xtend.core project. Strange that Maven does not show a more meaningful error message about this. The build is green after switching to xtend-maven-plugin `2.11.0.RC1`.
